### ISSUE TITLE
Referencing Phonetisaurus within Python3

### ISSUE THREAD

**Issue by aplawson** [AdolfVonKleist/Phonetisaurus#56]
I installed successfully with Python3 bindings but unable to reference it within Python3. It installed in dist- and site-packages but I'm unable to point to import it within Python scripts. Is this a bug with how it populates these directories or my implementation?
``$ ls /usr/local/lib/python3.7/dist-packages | grep 'phon\|Phon'
phonetisaurus-0.3-py3.7.egg
$ Traceback (most recent call last):
  File "./jasper.py", line 12, in <module>
    from client import stt
  File "/home/pi/jasper/client/stt.py", line 17, in <module>
    from . import vocabcompiler
  File "/home/pi/jasper/client/vocabcompiler.py", line 23, in <module>
    import phonetisaurus
  File "/usr/local/lib/python3.7/dist-packages/phonetisaurus-0.3-py3.7.egg/phonetisaurus/__init__.py", line 1, in <module>
    from Phonetisaurus import PhonetisaurusScript as Phonetisaurus
ModuleNotFoundError: No module named 'Phonetisaurus'```

**Comment by Mic92** [comment]
It is weird that it installs .a archives to site-packages. Python cannot handle those.
